"""CORQ daily runtime with side safety.

Hard rule:
- player1 = home/API first side
- player2 = away/API second side
- pick/opponent are derived from pick_side by corq.sides
- THINQ receives pick/opponent and side audit for candidate-side calculations
"""
from __future__ import annotations

import argparse
import importlib
import inspect
import json
import os
import re
import traceback
import unicodedata
from datetime import date, datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo
from pathlib import Path
from typing import Any, Dict, List, Optional

from corq.candidates import load_candidates
from corq.model import apply_corq_market_calibration, build_corq_prediction
from corq.outputs import save_all, save_run_manifest, save_top7
from corq.ranking import make_all_match_view, rank_corq, top7_from_ranking
from corq.sides import build_side_audit, repair_candidate_side


THINQ_SERVICE_LOAD_DIAGNOSTICS: List[Dict[str, Any]] = []


class _UnavailableThinqService:
    """Non-crashing service placeholder used only when all imports fail.

    This keeps the daily web build alive while making the failure explicit in
    outputs/latest_*.json and in the run manifest. Returning a structured
    payload is safer than silently producing 0%/N/A values without an import
    reason.
    """

    def __init__(self, diagnostics: List[Dict[str, Any]]) -> None:
        self._corq_import_module = None
        self._corq_import_file = None
        self._corq_import_diagnostics = diagnostics

    def build_match_features(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:
        return {
            "available": False,
            "thinq_available": False,
            "error": "THINQ_SERVICE_IMPORT_FAILED",
            "flags": ["THINQ_SERVICE_IMPORT_FAILED"],
            "thinq_flags": ["THINQ_SERVICE_IMPORT_FAILED"],
            "thinq_service_import_diagnostics": self._corq_import_diagnostics,
        }


def _load_thinq_service():
    """Load exactly one ThinQ service implementation, with diagnostics.

    The canonical implementation is `thinq.service`. `corq.service` must be a
    compatibility wrapper only. This loader records the module path so future
    path mix-ups are visible in the manifest and in enriched rows.
    """
    global THINQ_SERVICE_LOAD_DIAGNOSTICS
    THINQ_SERVICE_LOAD_DIAGNOSTICS = []
    candidates = (
        "thinq.service",
        "corq.service",
        "thinq.thinq_service",
    )
    for module_name in candidates:
        try:
            module = importlib.import_module(module_name)
            service_cls = getattr(module, "ThinqService")
            service = service_cls()
            setattr(service, "_corq_import_module", module_name)
            setattr(service, "_corq_import_file", getattr(module, "__file__", None))
            setattr(service, "_corq_import_diagnostics", list(THINQ_SERVICE_LOAD_DIAGNOSTICS))
            return service
        except Exception as exc:
            THINQ_SERVICE_LOAD_DIAGNOSTICS.append({
                "module": module_name,
                "ok": False,
                "error": f"{type(exc).__name__}: {exc}",
                "traceback_tail": traceback.format_exc(limit=4).splitlines()[-8:],
            })
    return _UnavailableThinqService(list(THINQ_SERVICE_LOAD_DIAGNOSTICS))


def _ranking_norm_name(value: Any) -> str:
    """Normalize player names for info-only ranking lookup.

    Ranking is intentionally NOT used in model probability or TOP7 ranking score.
    This lookup only replaces the old TA ranking display/cache dependency.
    """
    text = str(value or "").strip().lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def _ranking_compact_name(value: Any) -> str:
    return _ranking_norm_name(value).replace(" ", "")


def _to_int_or_none(value: Any) -> Optional[int]:
    try:
        if value in (None, "", "—", "-", "N/A"):
            return None
        return int(float(str(value).replace(",", "")))
    except Exception:
        return None


def _extract_tennisapi_ranking_rows(payload: Any) -> List[Dict[str, Any]]:
    """Extract ranking rows from several known/probable TennisApi shapes.

    Supported shapes include:
    - {"players_by_name": {...}} cache generated by update-ta-rankings.yml replacement
    - {"rankings": [...]}
    - {"data": [...]}
    - nested lists/dicts containing ranking/team/player fields
    """
    rows: List[Dict[str, Any]] = []
    if isinstance(payload, dict):
        players_by_name = payload.get("players_by_name")
        if isinstance(players_by_name, dict):
            for item in players_by_name.values():
                if isinstance(item, dict):
                    rows.append(item)
            return rows
        for key in ("rankings", "data", "result", "results", "items"):
            value = payload.get(key)
            if isinstance(value, list):
                for item in value:
                    rows.extend(_extract_tennisapi_ranking_rows(item))
            elif isinstance(value, dict):
                rows.extend(_extract_tennisapi_ranking_rows(value))
        if any(k in payload for k in ("ranking", "rank", "position", "rankingPoints", "points", "team", "player")):
            rows.append(payload)
    elif isinstance(payload, list):
        for item in payload:
            rows.extend(_extract_tennisapi_ranking_rows(item))
    return rows


def _ranking_row_to_player(row: Dict[str, Any], tour_hint: Optional[str] = None) -> Optional[Dict[str, Any]]:
    team = row.get("team") if isinstance(row.get("team"), dict) else {}
    player = row.get("player") if isinstance(row.get("player"), dict) else {}
    entity = team or player
    name = (
        row.get("name")
        or row.get("playerName")
        or row.get("teamName")
        or entity.get("name")
        or entity.get("shortName")
    )
    if not name:
        return None
    rank = _to_int_or_none(row.get("ranking") or row.get("rank") or row.get("position"))
    points = _to_int_or_none(row.get("points") or row.get("rankingPoints") or row.get("ranking_points"))
    if rank is None and points is None:
        return None
    category = row.get("category") if isinstance(row.get("category"), dict) else {}
    tour = (
        tour_hint
        or row.get("tour")
        or row.get("ranking_category")
        or category.get("name")
        or category.get("slug")
        or row.get("categoryName")
    )
    player_id = row.get("id") or row.get("player_id") or entity.get("id")
    out = {
        "name": str(name),
        "norm_name": _ranking_norm_name(name),
        "compact_name": _ranking_compact_name(name),
        "rank": rank,
        "points": points,
        "tour": str(tour).upper() if tour else None,
        "player_id": player_id,
        "country": (entity.get("country") or {}).get("name") if isinstance(entity.get("country"), dict) else entity.get("country"),
        "source": row.get("source") or "TENNISAPI_RANKINGS",
    }
    return out


def _load_tennisapi_rankings_info(output_root: str = "outputs") -> Dict[str, Any]:
    """Load info-only rankings generated from TennisApi.

    This intentionally replaces only the old TA ranking cache/update workflow.
    It does not affect CorQ/ThinQ/MMx probabilities or ranking score.
    """
    candidate_paths = [
        Path(output_root) / "rankings" / "tennisapi_rankings.json",
        Path("data/api_pro/rankings/tennisapi_rankings.json"),
        Path("data/rankings/tennisapi_rankings.json"),
        Path("outputs/tennisapi_rankings.json"),
    ]
    source_path = None
    payload: Any = None
    for path in candidate_paths:
        try:
            if path.exists():
                payload = json.loads(path.read_text(encoding="utf-8"))
                source_path = path
                break
        except Exception:
            continue
    players_by_name: Dict[str, Dict[str, Any]] = {}
    players_by_compact: Dict[str, Dict[str, Any]] = {}
    if payload is not None:
        raw_rows = _extract_tennisapi_ranking_rows(payload)
        for row in raw_rows:
            if isinstance(row, dict):
                player = _ranking_row_to_player(row)
                if not player:
                    continue
                if player["norm_name"]:
                    players_by_name[player["norm_name"]] = player
                if player["compact_name"]:
                    players_by_compact[player["compact_name"]] = player
    return {
        "status": "OK" if players_by_name else "NO_RANKING_CACHE",
        "source": "TENNISAPI_RANKINGS",
        "source_path": str(source_path) if source_path else None,
        "players_by_name": players_by_name,
        "players_by_compact": players_by_compact,
        "player_count": len(players_by_name),
    }


def _lookup_ranking_player(rankings: Dict[str, Any], name: Any) -> Optional[Dict[str, Any]]:
    if not isinstance(rankings, dict):
        return None
    norm = _ranking_norm_name(name)
    compact = _ranking_compact_name(name)
    by_name = rankings.get("players_by_name") if isinstance(rankings.get("players_by_name"), dict) else {}
    by_compact = rankings.get("players_by_compact") if isinstance(rankings.get("players_by_compact"), dict) else {}
    return by_name.get(norm) or by_compact.get(compact)


def _enrich_with_tennisapi_ranking_info(record: Dict[str, Any], rankings: Dict[str, Any]) -> Dict[str, Any]:
    """Attach current rank/points info only.

    No probability, confidence or TOP7 ranking logic is changed here.
    Compatibility TA display aliases are kept so existing UI does not break.
    """
    pick_name = record.get("pick") or record.get("player") or record.get("player1")
    opponent_name = record.get("opponent") or record.get("opp") or record.get("player2")
    pick_row = _lookup_ranking_player(rankings, pick_name)
    opp_row = _lookup_ranking_player(rankings, opponent_name)
    pick_rank = _to_int_or_none((pick_row or {}).get("rank"))
    opp_rank = _to_int_or_none((opp_row or {}).get("rank"))
    pick_points = _to_int_or_none((pick_row or {}).get("points"))
    opp_points = _to_int_or_none((opp_row or {}).get("points"))
    record["ranking_source"] = "TENNISAPI_RANKINGS"
    record["ranking_status"] = "OK" if pick_rank is not None or opp_rank is not None else rankings.get("status", "NO_RANKING_CACHE")
    record["ranking_cache_path"] = rankings.get("source_path")
    record["pick_rank"] = pick_rank
    record["opponent_rank"] = opp_rank
    record["pick_rank_points"] = pick_points
    record["opponent_rank_points"] = opp_points
    record["rank_gap"] = (opp_rank - pick_rank) if pick_rank is not None and opp_rank is not None else None
    record["rank_points_gap"] = (pick_points - opp_points) if pick_points is not None and opp_points is not None else None
    record["pick_rank_display"] = f"#{pick_rank}" if pick_rank is not None else "(X)"
    record["opponent_rank_display"] = f"#{opp_rank}" if opp_rank is not None else "(X)"
    record["pick_rank_points_display"] = str(pick_points) if pick_points is not None else "N/A"
    record["opponent_rank_points_display"] = str(opp_points) if opp_points is not None else "N/A"
    # Backward-compatible aliases for render code that still expects TA rank display keys.
    record["pick_ta_rank_display"] = record["pick_rank_display"]
    record["opponent_ta_rank_display"] = record["opponent_rank_display"]
    record["ta_ranking_replaced_by"] = "TENNISAPI_RANKINGS_INFO_ONLY"
    return record



def _enrich_with_ta_profile_context(record: Dict[str, Any]) -> Dict[str, Any]:
    """TA legacy disabled.

    Tennis Abstract profile enrichment was removed from the production path.
    Keep neutral ta_* compatibility fields so render/audit code that still reads
    those keys does not fail, but do not import or scrape TA data.
    """
    defaults = {
        "ta_status": "DISABLED",
        "ta_pick_status": "DISABLED",
        "ta_opp_status": "DISABLED",
        "ta_scope": "DISABLED",
        "ta_surface": None,
        "ta_pick_set_pct": None,
        "ta_opp_set_pct": None,
        "ta_pick_game_pct": None,
        "ta_opp_game_pct": None,
        "ta_pick_tb_split": None,
        "ta_opp_tb_split": None,
        "ta_pick_tb_pct": None,
        "ta_opp_tb_pct": None,
        "ta_pick_ace_pct": None,
        "ta_opp_ace_pct": None,
        "ta_pick_df_pct": None,
        "ta_opp_df_pct": None,
        "ta_pick_surface_dr": None,
        "ta_opp_surface_dr": None,
        "ta_pick_rpw_pct": None,
        "ta_opp_rpw_pct": None,
        "ta_pick_tpw_pct": None,
        "ta_opp_tpw_pct": None,
        "ta_pick_matches": None,
        "ta_opp_matches": None,
        "ta_pick_depth": None,
        "ta_opp_depth": None,
        "pick_aces_line": None,
        "opponent_aces_line": None,
        "total_aces_line": None,
        "aces_status": "N/A",
        "ta_winner_decision": "N/A",
        "ta_winner_read": "N/A",
        "ta_sets_decision": "N/A",
        "ta_games_decision": "N/A",
        "ta_tb_decision": "N/A",
        "ta_serve_return_pattern": "N/A",
        "ta_match_shape": "N/A",
        "ta_depth_label": "N/A",
        "ta_decision_confidence": 0.0,
        "ta_decision_notes": ["TA profile enrichment disabled; API/ThinQ data only"],
        "ta_context": {},
    }
    for key, value in defaults.items():
        record.setdefault(key, value)
    return record

def _call_build_match_features(thinq_service: Any, payload: Dict[str, Any]) -> Dict[str, Any]:
    method = thinq_service.build_match_features
    try:
        signature = inspect.signature(method)
        accepted = set(signature.parameters.keys())
        accepts_kwargs = any(
            parameter.kind == inspect.Parameter.VAR_KEYWORD
            for parameter in signature.parameters.values()
        )
        filtered = dict(payload) if accepts_kwargs else {key: value for key, value in payload.items() if key in accepted}
        return method(**filtered)
    except Exception:
        return method(
            player1=payload.get("player1"),
            player2=payload.get("player2"),
            surface=payload.get("surface"),
            level=payload.get("level"),
            event_id=payload.get("event_id"),
            best_of=payload.get("best_of") or 3,
        )


def _nested_get(data: Any, *keys: str) -> Any:
    current = data
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def _raw_dict(record: Dict[str, Any]) -> Dict[str, Any]:
    raw = record.get("raw")
    return raw if isinstance(raw, dict) else {}


def _event_custom_id(record: Dict[str, Any]) -> Optional[str]:
    raw = _raw_dict(record)
    candidates = [
        record.get("event_custom_id"),
        record.get("custom_id"),
        record.get("customId"),
        raw.get("customId"),
        raw.get("custom_id"),
        _nested_get(record, "event", "customId"),
        _nested_get(record, "match", "customId"),
    ]
    for candidate in candidates:
        if candidate in (None, ""):
            continue
        text = str(candidate).strip()
        if text:
            return text
    return None


def _raw_team_id(record: Dict[str, Any], side: str) -> Any:
    raw = _raw_dict(record)
    key = "homeTeam" if side == "HOME" else "awayTeam"
    team = raw.get(key) if isinstance(raw.get(key), dict) else {}
    if team.get("id") not in (None, ""):
        return team.get("id")
    info = team.get("playerTeamInfo") if isinstance(team.get("playerTeamInfo"), dict) else {}
    return info.get("id")


def _first_present(*values: Any) -> Any:
    for value in values:
        if value not in (None, ""):
            return value
    return None




def _first_from_dict(data: Dict[str, Any], *keys: str) -> Any:
    for key in keys:
        value = data.get(key)
        if value not in (None, ""):
            return value
    return None


def _copy_present(dst: Dict[str, Any], src: Dict[str, Any], key: str, alias: Optional[str] = None, overwrite: bool = False) -> None:
    out_key = alias or key
    if not overwrite and dst.get(out_key) not in (None, ""):
        return
    value = src.get(key)
    if value not in (None, ""):
        dst[out_key] = value


def _copy_many(dst: Dict[str, Any], src: Dict[str, Any], keys: List[str], overwrite: bool = False) -> None:
    for key in keys:
        _copy_present(dst, src, key, overwrite=overwrite)


def _num(value: Any) -> Optional[float]:
    try:
        if value in (None, "", "—", "-"):
            return None
        return float(value)
    except Exception:
        return None


def _pct_alias(value: Any) -> Optional[float]:
    number = _num(value)
    if number is None:
        return None
    return round(number * 100.0, 4) if abs(number) <= 1.0 else round(number, 4)


def _flatten_thinq_payload(record: Dict[str, Any], thinq: Dict[str, Any]) -> None:
    """Robust one-way bridge from ThinqService output to render/ranking rows.

    The service intentionally returns both nested diagnostic sections and flat
    compatibility fields. Older engine versions copied only thinq_* fields,
    which made the web render show 0%/N/A even when the nested service payload
    contained valid Elo, recent form, TA/API serve stats and model confidence.
    This flattener keeps the nested payload intact and also exposes every field
    that the CorQ cards, TOP7 ranking and Sets/Games/Aces/DF boxes consume.
    """
    if not isinstance(thinq, dict):
        return

    # Keep important nested contexts top-level as well. Render helpers check both.
    for ctx_key in (
        "elo",
        "surface",
        "h2h",
        "recent_form",
        "match_dynamics",
        "thinq_probability_layer",
        "ta_context",
        "api_serve_stats",
        "edges",
    ):
        value = thinq.get(ctx_key)
        if isinstance(value, dict):
            record.setdefault(ctx_key, value)

    flat_keys = [
        # ThinQ probability/confidence
        "confidence", "thinq_confidence", "thinq_data_confidence", "thinq_data_confidence_pct",
        "thinq_pick_probability", "thinq_pick_probability_pct", "thinq_probability", "thinq_probability_pct",
        # Elo / H2H / form / dynamics fields used by render and ranking
        "overall_pick_elo", "overall_opponent_elo", "surface_pick_elo", "surface_opponent_elo",
        "pick_elo", "opponent_elo", "overall_elo_diff", "surface_elo_diff", "elo_diff",
        "overall_elo_edge", "surface_elo_edge", "elo_edge", "h2h_edge", "surface_h2h_edge",
        "pick_last5_record", "opponent_last5_record", "pick_last10_record", "opponent_last10_record",
        "pick_surface_record", "opponent_surface_record", "pick_last10_win_pct", "opponent_last10_win_pct",
        "pick_surface_last10_win_pct", "opponent_surface_last10_win_pct",
        "recent_form_edge", "short_form_edge", "surface_recent_form_edge", "opponent_quality_edge",
        "form_confidence", "form_data_depth", "recent_form_status", "recent_form_reason",
        "projected_sets", "projected_games", "tiebreak_probability", "decider_probability", "straight_sets_probability",
        "sets_edge", "games_edge", "tiebreak_edge", "decider_edge", "match_shape",
        # TA and serve stats
        "ta_status", "ta_pick_status", "ta_opp_status", "ta_scope", "ta_surface",
        "ta_pick_set_pct", "ta_opp_set_pct", "ta_pick_game_pct", "ta_opp_game_pct",
        "ta_pick_tb_pct", "ta_opp_tb_pct", "ta_pick_tb_split", "ta_opp_tb_split",
        "ta_pick_ace_pct", "ta_opp_ace_pct", "ta_pick_df_pct", "ta_opp_df_pct",
        "ta_pick_surface_dr", "ta_opp_surface_dr", "ta_pick_rpw_pct", "ta_opp_rpw_pct",
        "ta_pick_depth", "ta_opp_depth", "ta_pick_matches", "ta_opp_matches",
        "s_data_depth", "sets_games_data_depth", "sets_model_source",
        "api_serve_stats_source", "api_serve_stats_status", "api_pick_serve_stats_status", "api_opp_serve_stats_status",
        "api_pick_ace_pct", "api_opp_ace_pct", "api_pick_df_pct", "api_opp_df_pct",
        "api_pick_aces_total", "api_opp_aces_total", "api_pick_double_faults_total", "api_opp_double_faults_total",
        "api_pick_aces_per_match", "api_opp_aces_per_match", "api_pick_double_faults_per_match", "api_opp_double_faults_per_match",
        "api_pick_stat_matches_played", "api_opp_stat_matches_played",
        "api_pick_return_pts_win_pct", "api_opp_return_pts_win_pct",
        "api_pick_first_serve_pct", "api_opp_first_serve_pct",
        "api_pick_winning_first_serve_pct", "api_opp_winning_first_serve_pct",
        "api_pick_winning_second_serve_pct", "api_opp_winning_second_serve_pct",
        "api_pick_serve_matches", "api_opp_serve_matches", "api_pick_serve_attempts", "api_opp_serve_attempts",
        "api_pick_serve_scope", "api_opp_serve_scope", "api_pick_serve_year", "api_opp_serve_year",
        "pick_ace_pct", "opponent_ace_pct", "pick_df_pct", "opponent_df_pct", "pick_tb_pct", "opponent_tb_pct",
        "pick_aces_line", "opponent_aces_line", "total_aces_line",
        "pick_aces_projection", "opponent_aces_projection", "total_aces_projection",
        "pick_df_projection", "opponent_df_projection", "total_df_projection",
        "ace_status", "df_status", "aces_status",
    ]
    _copy_many(record, thinq, flat_keys)

    prob_layer = thinq.get("thinq_probability_layer") if isinstance(thinq.get("thinq_probability_layer"), dict) else {}
    elo = thinq.get("elo") if isinstance(thinq.get("elo"), dict) else {}
    recent = thinq.get("recent_form") if isinstance(thinq.get("recent_form"), dict) else {}
    dynamics = thinq.get("match_dynamics") if isinstance(thinq.get("match_dynamics"), dict) else {}
    ta_ctx = thinq.get("ta_context") if isinstance(thinq.get("ta_context"), dict) else {}
    api_stats = thinq.get("api_serve_stats") if isinstance(thinq.get("api_serve_stats"), dict) else {}

    # Probability and confidence aliases.
    pick_prob = _first_from_dict(thinq, "thinq_pick_probability", "thinq_probability")
    if pick_prob in (None, ""):
        pick_prob = _first_from_dict(prob_layer, "pick_probability", "probability", "model_probability")
    if pick_prob not in (None, ""):
        record.setdefault("thinq_pick_probability", pick_prob)
        record.setdefault("thinq_probability", pick_prob)
        pct = _pct_alias(pick_prob)
        if pct is not None:
            record.setdefault("thinq_pick_probability_pct", pct)
            record.setdefault("thinq_probability_pct", pct)

    conf = _first_from_dict(thinq, "thinq_data_confidence", "thinq_confidence", "confidence")
    if conf in (None, ""):
        conf = _first_from_dict(prob_layer, "confidence", "data_confidence")
    if conf not in (None, ""):
        record.setdefault("thinq_confidence", conf)
        record.setdefault("thinq_data_confidence", conf)
        pct = _pct_alias(conf)
        if pct is not None:
            record.setdefault("thinq_data_confidence_pct", pct)

    # Flatten nested Elo, recent form, dynamics, TA and API serve contexts.
    _copy_many(record, elo, [
        "overall_pick_elo", "overall_opponent_elo", "surface_pick_elo", "surface_opponent_elo",
        "pick_elo", "opponent_elo", "overall_elo_diff", "surface_elo_diff", "elo_diff",
        "overall_elo_edge", "surface_elo_edge", "elo_edge", "selected_elo_type",
    ])
    _copy_many(record, recent, [
        "pick_last5_record", "opponent_last5_record", "pick_last10_record", "opponent_last10_record",
        "pick_surface_record", "opponent_surface_record", "pick_last10_win_pct", "opponent_last10_win_pct",
        "pick_surface_last10_win_pct", "opponent_surface_last10_win_pct",
        "recent_form_edge", "short_form_edge", "surface_recent_form_edge", "opponent_quality_edge",
        "form_confidence", "form_data_depth", "status", "reason",
    ])
    if recent.get("status") not in (None, ""):
        record.setdefault("recent_form_status", recent.get("status"))
        record.setdefault("thinq_recent_form_status", recent.get("status"))
    if recent.get("reason") not in (None, ""):
        record.setdefault("recent_form_reason", recent.get("reason"))
        record.setdefault("thinq_recent_form_reason", recent.get("reason"))

    _copy_many(record, dynamics, [
        "projected_sets", "projected_games", "tiebreak_probability", "decider_probability", "straight_sets_probability",
        "sets_edge", "games_edge", "tiebreak_edge", "decider_edge", "match_shape", "confidence",
    ])

    _copy_many(record, ta_ctx, [
        "ta_status", "ta_pick_status", "ta_opp_status", "ta_scope", "ta_surface",
        "ta_pick_set_pct", "ta_opp_set_pct", "ta_pick_game_pct", "ta_opp_game_pct",
        "ta_pick_tb_pct", "ta_opp_tb_pct", "ta_pick_tb_split", "ta_opp_tb_split",
        "ta_pick_ace_pct", "ta_opp_ace_pct", "ta_pick_df_pct", "ta_opp_df_pct",
        "ta_pick_depth", "ta_opp_depth", "ta_pick_matches", "ta_opp_matches",
        # Do not copy generic ace/DF aliases from TA here. API serve stats below
        # must win those public fields; TA remains only ta_* fallback.
        "pick_aces_line", "opponent_aces_line", "total_aces_line", "aces_status",
    ])

    _copy_many(record, api_stats, [
        "api_serve_stats_source", "api_serve_stats_status", "api_pick_serve_stats_status", "api_opp_serve_stats_status",
        "api_pick_ace_pct", "api_opp_ace_pct", "api_pick_df_pct", "api_opp_df_pct",
        "api_pick_aces_total", "api_opp_aces_total", "api_pick_double_faults_total", "api_opp_double_faults_total",
        "api_pick_aces_per_match", "api_opp_aces_per_match", "api_pick_double_faults_per_match", "api_opp_double_faults_per_match",
        "api_pick_stat_matches_played", "api_opp_stat_matches_played",
        "api_pick_return_pts_win_pct", "api_opp_return_pts_win_pct",
        "api_pick_first_serve_pct", "api_opp_first_serve_pct",
        "api_pick_winning_first_serve_pct", "api_opp_winning_first_serve_pct",
        "api_pick_winning_second_serve_pct", "api_opp_winning_second_serve_pct",
        "api_pick_serve_matches", "api_opp_serve_matches", "api_pick_serve_attempts", "api_opp_serve_attempts",
        "api_pick_serve_scope", "api_opp_serve_scope", "api_pick_serve_year", "api_opp_serve_year",
        "api_h2h_primary_status", "api_h2h_primary_path", "api_h2h_fallback_status", "api_h2h_resolution",
        "pick_aces_projection", "opponent_aces_projection", "total_aces_projection",
        "pick_df_projection", "opponent_df_projection", "total_df_projection", "aces_status", "df_status",
    ])

    # Final compatibility aliases for Sets/Games/Aces/DF render.
    # API serve stats are the source of truth for ace/DF fields. TA profile values
    # remain available only as a legacy fallback because TA scraping was not
    # reliable enough for these serve metrics. Do not let stale TA aliases block
    # fresher API fields.
    for out_key, candidates in {
        "pick_ace_pct": ("api_pick_ace_pct", "pick_ace_pct", "ta_pick_ace_pct"),
        "opponent_ace_pct": ("api_opp_ace_pct", "opponent_ace_pct", "ta_opp_ace_pct"),
        "pick_df_pct": ("api_pick_df_pct", "pick_df_pct", "ta_pick_df_pct"),
        "opponent_df_pct": ("api_opp_df_pct", "opponent_df_pct", "ta_opp_df_pct"),
        "pick_aces_line": ("pick_aces_projection", "pick_aces_line"),
        "opponent_aces_line": ("opponent_aces_projection", "opponent_aces_line"),
        "total_aces_line": ("total_aces_projection", "total_aces_line"),
        "pick_df_line": ("pick_df_projection", "pick_df_line"),
        "opponent_df_line": ("opponent_df_projection", "opponent_df_line"),
        "total_df_line": ("total_df_projection", "total_df_line"),
    }.items():
        for key in candidates:
            value = record.get(key)
            if value not in (None, ""):
                record[out_key] = value
                if str(key).startswith("api_") or str(key).endswith("_projection"):
                    record[f"{out_key}_source"] = "API_SERVE_STATS"
                elif str(key).startswith("ta_"):
                    record[f"{out_key}_source"] = "TA_PROFILE_FALLBACK"
                else:
                    record[f"{out_key}_source"] = record.get(f"{out_key}_source") or "LEGACY_EXISTING"
                break

    # Data depth fallback: prefer API serve sample availability, then TA profile
    # depth. TA depth is retained only as a legacy fallback while we migrate the
    # Sets/Games/TA signal box away from Tennis Abstract profiles.
    if record.get("s_data_depth") in (None, "", 0, 0.0):
        p_matches = _num(record.get("api_pick_serve_matches"))
        o_matches = _num(record.get("api_opp_serve_matches"))
        if p_matches is not None and o_matches is not None and (p_matches > 0 or o_matches > 0):
            depth = min(((p_matches + o_matches) / 52.0), 1.0)
            record["s_data_depth"] = round(depth, 4)
            record.setdefault("sets_games_data_depth", record["s_data_depth"])
            record.setdefault("sets_model_source", "API_SERVE_STATS_DEPTH")
        else:
            p_depth = _num(record.get("ta_pick_depth"))
            o_depth = _num(record.get("ta_opp_depth"))
            if p_depth is not None and o_depth is not None:
                record["s_data_depth"] = round((p_depth + o_depth) / 2.0, 4)
                record.setdefault("sets_games_data_depth", record["s_data_depth"])
                record.setdefault("sets_model_source", "TA_PROFILE_DEPTH_FALLBACK")


def _tour_type_token(record: Dict[str, Any]) -> Optional[str]:
    """Return atp/wta only from explicit API metadata, never guessed from names."""
    raw = _raw_dict(record)
    values = [
        record.get("tour_type"), record.get("gender"), record.get("category"), record.get("level"),
        _nested_get(raw, "homeTeam", "gender"), _nested_get(raw, "awayTeam", "gender"),
        _nested_get(raw, "tournament", "category", "name"),
        _nested_get(raw, "tournament", "uniqueTournament", "category", "name"),
    ]
    for value in values:
        text = str(value or "").strip().lower()
        if not text:
            continue
        if "wta" in text or text in {"women", "female", "womens", "ladies"}:
            return "wta"
        if "atp" in text or text in {"men", "male", "mens"}:
            return "atp"
    return None


def _surface_token_for_h2h(record: Dict[str, Any]) -> Optional[str]:
    surface = str(record.get("surface") or record.get("surface_raw") or "").strip().lower()
    if not surface:
        return None
    if "clay" in surface:
        return "clay"
    if "grass" in surface:
        return "grass"
    if "carpet" in surface:
        return "carpet"
    if "hard" in surface:
        return "hard"
    return None


def _side_map_value(stats: Dict[str, Any], side: str, key: str) -> Any:
    prefix = "player1" if side == "HOME" else "player2"
    return stats.get(f"{prefix}_{key}")


def _apply_api_h2h_stats_to_record(record: Dict[str, Any], stats: Dict[str, Any]) -> Dict[str, Any]:
    """Attach TennisAPI H2H stats without fabricating missing values.

    Aces and double faults from the endpoint are totals/per-match, not
    percentages. Therefore this function writes explicit *_total and
    *_per_match fields and does NOT populate *_ace_pct / *_df_pct unless a real
    percentage exists in the API payload.
    """
    if not isinstance(stats, dict):
        return record
    record["api_serve_stats"] = stats
    for key, value in stats.items():
        if key.startswith("api_"):
            record[key] = value

    pick_side = str(record.get("pick_side") or "HOME").upper()
    opp_side = str(record.get("opponent_side") or ("AWAY" if pick_side == "HOME" else "HOME")).upper()
    if pick_side not in {"HOME", "AWAY"}:
        pick_side = "HOME"
    if opp_side not in {"HOME", "AWAY"}:
        opp_side = "AWAY" if pick_side == "HOME" else "HOME"

    side_fields = {
        "aces_total": "aces_total",
        "double_faults_total": "double_faults_total",
        "aces_per_match": "aces_per_match",
        "double_faults_per_match": "double_faults_per_match",
        "stat_matches_played": "stat_matches_played",
        "first_serve_pct": "first_serve_pct",
        "winning_first_serve_pct": "winning_first_serve_pct",
        "winning_second_serve_pct": "winning_second_serve_pct",
        "return_pts_win_pct": "return_pts_win_pct",
        "breakpoints_won_pct": "breakpoints_won_pct",
        "tiebreak_won": "tiebreak_won",
        "tiebreak_count": "tiebreak_count",
        "sets_won": "sets_won",
        "games_won": "games_won",
        "matches_won": "matches_won",
    }
    for out_suffix, src_key in side_fields.items():
        pick_val = _side_map_value(stats, pick_side, src_key)
        opp_val = _side_map_value(stats, opp_side, src_key)
        if pick_val not in (None, ""):
            record[f"api_pick_{out_suffix}"] = pick_val
        if opp_val not in (None, ""):
            record[f"api_opp_{out_suffix}"] = opp_val

    # Compatibility fields for s_data_depth only. These are sample counts, not fake percentages.
    if record.get("api_pick_stat_matches_played") not in (None, ""):
        record["api_pick_serve_matches"] = record.get("api_pick_stat_matches_played")
    if record.get("api_opp_stat_matches_played") not in (None, ""):
        record["api_opp_serve_matches"] = record.get("api_opp_stat_matches_played")

    record["api_serve_stats_status"] = stats.get("api_serve_stats_status") or record.get("api_serve_stats_status")
    record["api_serve_stats_source"] = stats.get("api_serve_stats_source") or "TENNISAPI_H2H_STATS"
    return record


def _enrich_with_api_h2h_stats(record: Dict[str, Any], client: Any, request_state: Optional[Dict[str, int]] = None) -> Dict[str, Any]:
    """Fetch TennisAPI H2H serve/return stats as primary source.

    Provider note: keep daily H2H stats requests capped. No values are estimated
    when the cap, IDs, names or tour type are missing.
    """
    if client is None:
        record["api_serve_stats_status"] = "CLIENT_UNAVAILABLE"
        record["api_serve_stats_source"] = "TENNISAPI_H2H_STATS"
        return record
    state = request_state if isinstance(request_state, dict) else {"count": 0}
    try:
        max_requests = int(os.getenv("TENNISAPI_H2H_STATS_MAX_REQUESTS", "200"))
    except Exception:
        max_requests = 200
    max_requests = max(0, min(max_requests, 200))
    if state.get("count", 0) >= max_requests:
        record["api_serve_stats_status"] = "REQUEST_CAP_REACHED"
        record["api_serve_stats_source"] = "TENNISAPI_H2H_STATS"
        record["api_h2h_request_cap"] = max_requests
        return record

    tour = _tour_type_token(record)
    if not tour:
        record["api_serve_stats_status"] = "MISSING_TOUR_TYPE"
        record["api_serve_stats_source"] = "TENNISAPI_H2H_STATS"
        return record

    raw = _raw_dict(record)
    p1 = record.get("player1")
    p2 = record.get("player2")
    p1_id = _first_present(record.get("player1_id"), record.get("player1Id"), _raw_team_id(record, "HOME"))
    p2_id = _first_present(record.get("player2_id"), record.get("player2Id"), _raw_team_id(record, "AWAY"))
    surface = _surface_token_for_h2h(record)

    stats: Dict[str, Any]
    state["count"] = int(state.get("count", 0)) + 1
    try:
        if p1_id not in (None, "") and p2_id not in (None, ""):
            stats = client.get_h2h_stats_by_ids(
                tour,
                p1_id,
                p2_id,
                surface=surface,
                player1_name=str(p1 or ""),
                player2_name=str(p2 or ""),
            )
        else:
            stats = client.get_h2h_stats_by_names(tour, str(p1 or ""), str(p2 or ""), surface=surface)
    except Exception as exc:
        stats = {"api_serve_stats_status": f"ERROR:{exc}", "api_serve_stats_source": "TENNISAPI_H2H_STATS"}
    record["api_h2h_stats_request_no"] = state.get("count")
    return _apply_api_h2h_stats_to_record(record, stats)

def _enrich_with_thinq(record: Dict[str, Any], thinq_service: Any) -> Dict[str, Any]:
    safe_record = repair_candidate_side(record)
    safe_record["side_audit"] = build_side_audit(safe_record)

    if thinq_service is None:
        safe_record["thinq"] = {"available": False, "error": "THINQ_SERVICE_UNAVAILABLE"}
        safe_record["thinq_available"] = False
        safe_record["thinq_error"] = "THINQ_SERVICE_UNAVAILABLE"
        safe_record["thinq_flags"] = ["THINQ_SERVICE_UNAVAILABLE"]
        return safe_record

    raw = _raw_dict(safe_record)
    event_custom_id = _event_custom_id(safe_record)
    event_id = _first_present(
        safe_record.get("event_id"),
        safe_record.get("match_id"),
        safe_record.get("id"),
        raw.get("id"),
    )

    payload = {
        "player1": safe_record.get("player1"),
        "player2": safe_record.get("player2"),
        "surface": safe_record.get("surface") or safe_record.get("surface_raw") or raw.get("groundType"),
        "level": safe_record.get("level") or safe_record.get("category") or _nested_get(raw, "tournament", "category", "name"),
        "tournament_url": safe_record.get("tournament_url"),
        "tour_type": safe_record.get("tour_type") or safe_record.get("gender") or _nested_get(raw, "homeTeam", "gender") or _nested_get(raw, "awayTeam", "gender"),
        "as_of_date": safe_record.get("date") or safe_record.get("match_date") or safe_record.get("match_start") or safe_record.get("start_time"),
        "event_id": event_id,
        "event_custom_id": event_custom_id,
        "custom_id": event_custom_id,
        "customId": event_custom_id,
        "player1_id": _first_present(safe_record.get("player1_id"), safe_record.get("player1Id"), _raw_team_id(safe_record, "HOME")),
        "player2_id": _first_present(safe_record.get("player2_id"), safe_record.get("player2Id"), _raw_team_id(safe_record, "AWAY")),
        "tournament_id": _first_present(safe_record.get("tournament_id"), safe_record.get("tournamentId"), _nested_get(raw, "tournament", "id")),
        "best_of": safe_record.get("best_of") or 3,
        "pick": safe_record.get("pick"),
        "opponent": safe_record.get("opponent"),
        "pick_side": safe_record.get("pick_side"),
        "opponent_side": safe_record.get("opponent_side"),
        "side_audit": safe_record.get("side_audit"),
        # Odds are part of the ThinQ match context. Do not force ThinQ to
        # rediscover them from raw payloads because side-safe candidates already
        # carry correctly oriented pick/opponent odds.
        "odds_player1": safe_record.get("odds_player1") or safe_record.get("p1_odds") or safe_record.get("odds1") or safe_record.get("home_odds"),
        "odds_player2": safe_record.get("odds_player2") or safe_record.get("p2_odds") or safe_record.get("odds2") or safe_record.get("away_odds"),
        "p1_odds": safe_record.get("p1_odds") or safe_record.get("odds_player1") or safe_record.get("home_odds"),
        "p2_odds": safe_record.get("p2_odds") or safe_record.get("odds_player2") or safe_record.get("away_odds"),
        "odds1": safe_record.get("odds1") or safe_record.get("odds_player1") or safe_record.get("home_odds"),
        "odds2": safe_record.get("odds2") or safe_record.get("odds_player2") or safe_record.get("away_odds"),
        "home_odds": safe_record.get("home_odds") or safe_record.get("odds_player1") or safe_record.get("p1_odds"),
        "away_odds": safe_record.get("away_odds") or safe_record.get("odds_player2") or safe_record.get("p2_odds"),
        "pick_odds": safe_record.get("pick_odds") or safe_record.get("odds"),
        "opponent_odds": safe_record.get("opponent_odds"),
        "odds": safe_record.get("odds") or safe_record.get("pick_odds"),
        "odds_pair_available": safe_record.get("odds_pair_available"),
        "odds_matching_direction": safe_record.get("odds_matching_direction"),
        "odds_labels_confirmed": safe_record.get("odds_labels_confirmed"),
        "status_type": safe_record.get("status_type"),
        "status_code": safe_record.get("status_code"),
        "match_start": safe_record.get("match_start") or safe_record.get("start_time"),
        "start_time": safe_record.get("start_time") or safe_record.get("match_start"),
        "raw": raw,
        "match_raw": raw,
        "raw_event": raw,
    }

    try:
        thinq = _call_build_match_features(thinq_service, payload)
        if not isinstance(thinq, dict):
            thinq = {"available": False, "error": "THINQ_RETURNED_NON_DICT"}
    except Exception as exc:
        thinq = {"available": False, "error": str(exc), "flags": ["THINQ_ATTACH_FAILED"]}

    safe_record["thinq"] = thinq
    safe_record["thinq_service_module"] = getattr(thinq_service, "_corq_import_module", None)
    safe_record["thinq_service_file"] = getattr(thinq_service, "_corq_import_file", None)
    safe_record["thinq_service_import_diagnostics"] = getattr(thinq_service, "_corq_import_diagnostics", [])
    safe_record["thinq_available"] = bool(thinq.get("available", thinq.get("thinq_available", False)))
    safe_record["thinq_error"] = thinq.get("error")
    safe_record["thinq_confidence"] = thinq.get("confidence") or thinq.get("thinq_confidence")
    safe_record["thinq_edges"] = thinq.get("edges") if isinstance(thinq.get("edges"), dict) else {}
    safe_record["thinq_flags"] = thinq.get("flags") or thinq.get("thinq_flags") or []
    # Flatten data-source status for easier web/debug inspection.
    safe_record["thinq_elo_status"] = _nested_get(thinq, "elo", "status") or thinq.get("thinq_elo_status")
    safe_record["thinq_recent_form_status"] = _nested_get(thinq, "recent_form", "status") or thinq.get("thinq_recent_form_status")
    safe_record["thinq_recent_form_reason"] = _nested_get(thinq, "recent_form", "reason") or thinq.get("thinq_recent_form_reason")
    safe_record["thinq_history_match_count"] = _nested_get(thinq, "recent_form", "history_status", "match_count")
    safe_record["thinq_history_file_count"] = _nested_get(thinq, "recent_form", "history_status", "file_count")
    safe_record["thinq_match_dynamics_status"] = _nested_get(thinq, "match_dynamics", "status") or thinq.get("thinq_match_dynamics_status")
    safe_record["thinq_probability_layer_status"] = _nested_get(thinq, "thinq_probability_layer", "status") or thinq.get("thinq_probability_status")

    for key, value in thinq.items():
        if key.startswith("thinq_"):
            safe_record[key] = value

    _flatten_thinq_payload(safe_record, thinq)

    safe_record["thinq_h2h_requested_event_custom_id"] = (
        _nested_get(thinq, "h2h", "requested_event_custom_id")
        or thinq.get("thinq_h2h_requested_event_custom_id")
    )
    return safe_record






def _date_only_for_marq(record: Dict[str, Any]) -> str:
    for key in ("match_date", "date", "start_time_utc", "match_time_utc", "commence_time", "start_time", "match_time"):
        value = record.get(key)
        if value in (None, ""):
            continue
        text = str(value).strip()
        if len(text) >= 10:
            return text[:10]
    return date.today().isoformat()


def _decimal_odds(value: Any) -> Optional[float]:
    try:
        if value in (None, "", "—", "-"):
            return None
        number = float(str(value).replace(",", "."))
        if 1.01 <= number <= 100.0:
            return number
    except Exception:
        return None
    return None


def _no_vig_pair_from_odds(pick_odds: Any, opponent_odds: Any) -> tuple[Optional[float], Optional[float]]:
    pick = _decimal_odds(pick_odds)
    opp = _decimal_odds(opponent_odds)
    if pick is None or opp is None:
        return None, None
    p_raw = 1.0 / pick
    o_raw = 1.0 / opp
    total = p_raw + o_raw
    if total <= 0:
        return None, None
    return round((p_raw / total) * 100.0, 1), round((o_raw / total) * 100.0, 1)


def _fallback_marq_from_row(record: Dict[str, Any]) -> Dict[str, Any]:
    """Build a minimal MARQ view from already available match odds.

    This prevents empty MarQ boxes when bookmaker event lookup fails. It does
    not create movement or CLV because historical/current quote snapshots are
    required for those fields.
    """
    pick_odds = _first_present(record.get("pick_odds"), record.get("odds"))
    opponent_odds = _first_present(record.get("opponent_odds"), record.get("opp_odds"))
    if pick_odds is None or opponent_odds is None:
        pick_side = str(record.get("pick_side") or "").upper()
        if pick_side == "HOME":
            pick_odds = _first_present(record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds"))
            opponent_odds = _first_present(record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds"))
        elif pick_side == "AWAY":
            pick_odds = _first_present(record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds"))
            opponent_odds = _first_present(record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds"))
        else:
            pick_odds = _first_present(record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds"), pick_odds)
            opponent_odds = _first_present(record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds"), opponent_odds)
    pick_pct, opp_pct = _no_vig_pair_from_odds(pick_odds, opponent_odds)
    if pick_pct is None or opp_pct is None:
        return {}
    edge = round(pick_pct - 50.0, 1)
    final = "Market With Pick" if edge >= 2.0 else "Market Against Pick" if edge <= -2.0 else "Neutral"
    return {
        "marq_market_view": True,
        "marq_source": "RuntimeOddsFallback",
        "marq_market_name": "Match winner",
        "marq_provider_count": 1,
        "marq_crowd_pick_pct": pick_pct,
        "marq_crowd_opponent_pct": opp_pct,
        "marq_edge_pct": edge,
        "marq_move_signal": "PENDING",
        "marq_display_move_signal": "PENDING",
        "marq_movement_available": False,
        "marq_initial_pick_odds": None,
        "marq_current_pick_odds": _decimal_odds(pick_odds),
        "marq_initial_opponent_odds": None,
        "marq_current_opponent_odds": _decimal_odds(opponent_odds),
        "marq_move_range": None,
        "marq_market_move_pct": None,
        "marq_quality_signal": "ODDS ONLY",
        "marq_final": final,
        "marq_final_display": final,
        "marq_clv_status": "PENDING",
    }


def _odds_pair_for_pick_side(record: Dict[str, Any]) -> tuple[Optional[float], Optional[float]]:
    pick_side = str(record.get("pick_side") or "").upper()
    if pick_side == "HOME":
        pick_odds = _decimal_odds(_first_present(record.get("pick_odds"), record.get("odds"), record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds")))
        opp_odds = _decimal_odds(_first_present(record.get("opponent_odds"), record.get("opp_odds"), record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds")))
        return pick_odds, opp_odds
    if pick_side == "AWAY":
        pick_odds = _decimal_odds(_first_present(record.get("pick_odds"), record.get("odds"), record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds")))
        opp_odds = _decimal_odds(_first_present(record.get("opponent_odds"), record.get("opp_odds"), record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds")))
        return pick_odds, opp_odds
    return (
        _decimal_odds(_first_present(record.get("pick_odds"), record.get("odds"))),
        _decimal_odds(_first_present(record.get("opponent_odds"), record.get("opp_odds"))),
    )


def _home_away_odds_pair(record: Dict[str, Any]) -> tuple[Optional[float], Optional[float]]:
    home_odds = _decimal_odds(_first_present(record.get("odds_player1"), record.get("p1_odds"), record.get("odds1"), record.get("home_odds")))
    away_odds = _decimal_odds(_first_present(record.get("odds_player2"), record.get("p2_odds"), record.get("odds2"), record.get("away_odds")))
    if home_odds is None or away_odds is None:
        pick_odds, opp_odds = _odds_pair_for_pick_side(record)
        pick_side = str(record.get("pick_side") or "").upper()
        if pick_side == "HOME":
            return pick_odds, opp_odds
        if pick_side == "AWAY":
            return opp_odds, pick_odds
    return home_odds, away_odds


def _merge_marq_v2_market(output: Dict[str, Any], market: Dict[str, Any]) -> Dict[str, Any]:
    """Copy TennisApi-only MarQ V2 provider data into the CorQ row.

    Provider V2 returns exact-event market data with home/away no-vig odds. This
    bridge preserves all audit fields and also fills legacy MarQ fields used by
    rankings/render/results so the row no longer degrades to RuntimeOddsFallback.
    """
    for key, value in market.items():
        if value not in (None, ""):
            output[key] = value

    pick_key = str(market.get("pick_outcome_key") or output.get("pick_outcome_key") or "od1").lower()
    p1_prob = market.get("marq_no_vig_probability_1")
    p2_prob = market.get("marq_no_vig_probability_2")
    if p1_prob is None:
        p1_prob = market.get("marq_v2_no_vig_1")
    if p2_prob is None:
        p2_prob = market.get("marq_v2_no_vig_2")

    pick_prob = p2_prob if pick_key in {"od2", "2", "away"} else p1_prob
    opp_prob = p1_prob if pick_key in {"od2", "2", "away"} else p2_prob

    def pct(value: Any) -> Optional[float]:
        try:
            if value in (None, ""):
                return None
            number = float(value)
            return round(number * 100.0, 4) if abs(number) <= 1.0 else round(number, 4)
        except Exception:
            return None

    pick_pct = pct(pick_prob)
    opp_pct = pct(opp_prob)
    if pick_pct is not None:
        output["marq_crowd_pick_pct"] = round(pick_pct, 1)
        output["marq_pick_probability"] = round(pick_pct / 100.0, 6)
        output["marq_pick_no_vig_probability"] = round(pick_pct / 100.0, 6)
        output["market_pick_probability"] = round(pick_pct / 100.0, 6)
        output["corq_market_probability"] = round(pick_pct / 100.0, 6)
        output["marq_edge_pct"] = round(pick_pct - 50.0, 1)
    if opp_pct is not None:
        output["marq_crowd_opponent_pct"] = round(opp_pct, 1)
        output["marq_opp_no_vig_probability"] = round(opp_pct / 100.0, 6)

    # Fill display odds from provider when available, otherwise keep row odds.
    odds_block = market.get("odds") if isinstance(market.get("odds"), dict) else {}
    od1 = odds_block.get("od1") if isinstance(odds_block.get("od1"), dict) else {}
    od2 = odds_block.get("od2") if isinstance(odds_block.get("od2"), dict) else {}
    if od1.get("current") is not None:
        output["marq_current_odds_1"] = od1.get("current")
    if od2.get("current") is not None:
        output["marq_current_odds_2"] = od2.get("current")
    if od1.get("opening") is not None:
        output["marq_opening_odds_1"] = od1.get("opening")
    if od2.get("opening") is not None:
        output["marq_opening_odds_2"] = od2.get("opening")

    if output.get("marq_final") in (None, ""):
        edge = _num(output.get("marq_edge_pct"))
        if edge is not None:
            output["marq_final"] = "Market With Pick" if edge >= 2.0 else "Market Against Pick" if edge <= -2.0 else "Neutral"
            output["marq_final_display"] = output["marq_final"]

    output.setdefault("marq_market_view", True)
    output.setdefault("marq_provider_count", market.get("market_quote_count") or 1)
    output.setdefault("marq_market_name", "Match winner")
    output.setdefault("marq_quality_signal", market.get("marq_data_status") or market.get("marq_source_quality") or "TennisApi MarQ V2")
    return output


def _tag_thin_fallback(output: Dict[str, Any]) -> None:
    output.setdefault("marq_api_source", "existing row odds")
    output.setdefault("marq_source_policy", "ENGINE_THIN_FALLBACK_ONLY")
    output.setdefault("marq_source_quality", "FALLBACK_EXISTING_ODDS_THIN")
    output.setdefault("marq_data_status", "FALLBACK_EXISTING_ODDS_THIN")
    output.setdefault("marq_confidence", "LOW")
    output.setdefault("marq_movement_status", "NO_REAL_MOVEMENT_DATA_THIN_FALLBACK")
    output.setdefault("marq_exact_event_id_used", bool(output.get("event_id") or output.get("match_id") or output.get("id")))
    output.setdefault("marq_name_matching_skipped", True)
    output.setdefault("marq_date_feed_skipped", True)
    output.setdefault("marq_display_move_signal", "Current only")
    output.setdefault("marq_internal_move_signal", "Current only")
    output.setdefault("marq_move_signal", "Current only")


def _enrich_with_marq(record: Dict[str, Any]) -> Dict[str, Any]:
    """Attach TennisApi-only MarQ V2 fields to a scored match row.

    The previous flow called marq.pipeline without passing exact event context,
    so rows frequently degraded to RuntimeOddsFallback even though event ids and
    odds endpoint attempts existed. This implementation calls marq.provider
    directly with the full row context, preserving exact-event MarQ audit fields.
    """
    output = dict(record)
    event_id = _first_present(output.get("event_id"), output.get("match_id"), output.get("id"))
    home_odds, away_odds = _home_away_odds_pair(output)

    market: Optional[Dict[str, Any]] = None
    try:
        from marq.provider import fetch_marq_market_data  # type: ignore
        market = fetch_marq_market_data(
            player1=str(output.get("player1") or ""),
            player2=str(output.get("player2") or ""),
            date_only=_date_only_for_marq(output),
            pick=str(output.get("pick") or output.get("player") or "") or None,
            odds_player1=home_odds,
            odds_player2=away_odds,
            event_id=event_id,
            match_id=output.get("match_id"),
            tennisapi_event_id=output.get("tennisapi_event_id"),
            id=output.get("id"),
            raw=output.get("raw") if isinstance(output.get("raw"), dict) else None,
            row=output,
        )
    except Exception as exc:
        output.setdefault("marq_error", str(exc))

    if isinstance(market, dict) and market:
        output = _merge_marq_v2_market(output, market)
    else:
        fallback = _fallback_marq_from_row(output)
        if fallback:
            for key, value in fallback.items():
                output.setdefault(key, value)
            _tag_thin_fallback(output)

    if output.get("marq_edge_pct") in (None, ""):
        try:
            pick_pct = float(output.get("marq_crowd_pick_pct"))
            output["marq_edge_pct"] = round(pick_pct - 50.0, 1)
        except Exception:
            pass
    if output.get("marq_final") in (None, ""):
        try:
            edge = float(output.get("marq_edge_pct"))
            output["marq_final"] = "Market With Pick" if edge >= 2.0 else "Market Against Pick" if edge <= -2.0 else "Neutral"
            output["marq_final_display"] = output["marq_final"]
        except Exception:
            output.setdefault("marq_final", "Pending")

    # CLV snapshot enrichment is optional and must not overwrite MarQ V2 data.
    try:
        from marq.odds_snapshots import enrich_row_with_internal_marq  # type: ignore
        output = enrich_row_with_internal_marq(output)
    except Exception as exc:
        output.setdefault("marq_internal_error", str(exc))
    return output

def _enrich_with_sets_games(record: Dict[str, Any]) -> Dict[str, Any]:
    """Attach Sets/Games market-aware fields from marq.market_lines.

    This is intentionally soft-fail: if market helpers or upstream APIs are not
    available, the CORQ runtime continues and the renderer shows N/A/Pending.
    """
    try:
        from marq.market_lines import build_sets_games_from_match, build_sets_games_value_candidates  # type: ignore
    except Exception as exc:
        record.setdefault("sets_games_status", "UNAVAILABLE")
        record.setdefault("sets_games_error", str(exc))
        record.setdefault("sets_games_best_value", "Pending lines")
        return record

    try:
        model_prediction = {
            "probability_player1": record.get("probability_player1") or record.get("p1_probability") or record.get("player1_probability"),
            "probability_player2": record.get("probability_player2") or record.get("p2_probability") or record.get("player2_probability"),
        }
        enriched = build_sets_games_from_match(record, model_prediction=model_prediction)
        if isinstance(enriched, dict):
            record.update(enriched)
        value_candidates = build_sets_games_value_candidates(record)
        record["sets_games_value_candidates"] = value_candidates
        if value_candidates and value_candidates[0].get("selection"):
            record["sets_games_best_value"] = value_candidates[0].get("selection")
            record["sets_games_best_value_edge"] = value_candidates[0].get("edge")
        else:
            record.setdefault("sets_games_best_value", "Pending lines")
        record.setdefault("sets_games_status", "OK")
    except Exception as exc:
        record.setdefault("sets_games_status", "ERROR")
        record.setdefault("sets_games_error", str(exc))
        record.setdefault("sets_games_best_value", "Pending lines")
    return record


def _probability_ratio(value: Any) -> Optional[float]:
    num = _num(value)
    if num is None:
        return None
    if num > 1.0:
        num /= 100.0
    if 0.0 <= num <= 1.0:
        return num
    return None


def _first_probability_ratio(record: Dict[str, Any], *keys: str) -> Optional[float]:
    for key in keys:
        value = record.get(key)
        ratio = _probability_ratio(value)
        if ratio is not None:
            return ratio
    return None


def _price_bucket_label(odds: Optional[float]) -> str:
    if odds is None:
        return "Unknown"
    if odds < 1.50:
        return "Short"
    if odds <= 2.20:
        return "Fair"
    return "Long Risk"


def _value_bucket_label(delta_pp: Optional[float]) -> str:
    if delta_pp is None:
        return "Unknown"
    if delta_pp >= 3.0:
        return "Value+"
    if delta_pp >= -2.0:
        return "Neutral"
    return "No Value"


def _enrich_with_price_value(record: Dict[str, Any]) -> Dict[str, Any]:
    """Attach non-filtering betting-value audit fields.

    These fields do NOT select or reject picks. They only make price/value
    visible in CorQ, Audit and Results snapshots:
    - raw implied probability = 1 / pick odds
    - Value Delta = CorQ probability - raw implied probability
    - EV = CorQ probability * decimal odds - 1
    """
    odds = _decimal_odds(
        _first_present(
            record.get("pick_odds"),
            record.get("odds"),
            record.get("selected_odds"),
            record.get("odds_decimal"),
            record.get("decimal_odds"),
        )
    )
    corq_prob = _first_probability_ratio(
        record,
        "corq_calibrated_probability",
        "corq_probability",
        "corq_estimated_win_probability",
        "win_probability",
        "estimated_win_probability",
        "probability",
    )
    if odds is None or corq_prob is None or odds <= 0:
        record.setdefault("price_value_status", "MISSING_VALUE_INPUT")
        return record

    raw_implied = 1.0 / odds
    delta_pp = (corq_prob - raw_implied) * 100.0
    ev_ratio = (corq_prob * odds) - 1.0
    ev_pct = ev_ratio * 100.0

    price_bucket = _price_bucket_label(odds)
    value_bucket = _value_bucket_label(delta_pp)
    price_slug = price_bucket.upper().replace(" ", "_")
    value_slug = (
        "VALUE_POSITIVE" if value_bucket == "Value+" else
        "VALUE_NEUTRAL" if value_bucket == "Neutral" else
        "VALUE_NEGATIVE" if value_bucket == "No Value" else
        "VALUE_UNKNOWN"
    )

    record["raw_implied_probability"] = round(raw_implied, 6)
    record["raw_implied_probability_pct"] = round(raw_implied * 100.0, 2)
    record["break_even_probability"] = round(raw_implied, 6)
    record["break_even_probability_pct"] = round(raw_implied * 100.0, 2)
    record["corq_value_delta_pp"] = round(delta_pp, 2)
    record["expected_value"] = round(ev_ratio, 6)
    record["expected_value_pct"] = round(ev_pct, 2)
    record["price_value_grade"] = price_slug
    record["price_value_tag"] = value_slug
    record["price_value_display"] = f"{price_bucket} | {value_bucket}"
    record["price_value_status"] = "OK"
    tags = [price_slug, value_slug]
    existing = record.get("price_value_tags")
    if isinstance(existing, list):
        tags = list(dict.fromkeys([str(x) for x in existing if x] + tags))
    record["price_value_tags"] = tags
    return record

def _betting_day_context(run_date: Optional[str] = None) -> Dict[str, str]:
    """Return the Europe/Bratislava betting day window: 06:00 to 06:00.

    Matches after midnight but before 06:00 local time belong to the previous
    betting day. This is used for immutable morning snapshots and Results.
    """
    tz = ZoneInfo("Europe/Bratislava")
    if run_date:
        base_day = datetime.fromisoformat(str(run_date)[:10]).date()
    else:
        now = datetime.now(tz)
        base_day = now.date() - timedelta(days=1) if now.hour < 6 else now.date()
    start_local = datetime.combine(base_day, time(hour=6), tzinfo=tz)
    end_local = start_local + timedelta(days=1)
    return {
        "betting_day": base_day.isoformat(),
        "snapshot_date": base_day.isoformat(),
        "betting_day_start_local": start_local.isoformat(),
        "betting_day_end_local": end_local.isoformat(),
        "timezone": "Europe/Bratislava",
    }


def _snapshot_rows(rows: List[Dict[str, Any]], *, snapshot_type: str, context: Dict[str, str]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    snapshot_id = f"{snapshot_type}_{context['betting_day']}"
    created_at = datetime.now(timezone.utc).isoformat()
    for idx, row in enumerate(rows or [], start=1):
        if not isinstance(row, dict):
            continue
        item = dict(row)
        item.setdefault("snapshot_id", snapshot_id)
        item.setdefault("snapshot_type", snapshot_type)
        item.setdefault("snapshot_source", "CORQ_DAILY")
        item.setdefault("snapshot_rank", idx)
        item.setdefault("snapshot_date", context["snapshot_date"])
        item.setdefault("betting_day", context["betting_day"])
        item.setdefault("betting_day_start_local", context["betting_day_start_local"])
        item.setdefault("betting_day_end_local", context["betting_day_end_local"])
        item.setdefault("snapshot_timezone", context["timezone"])
        item.setdefault("snapshot_created_at_utc", created_at)
        item.setdefault("results_status", "PENDING")
        out.append(item)
    return out


SNAPSHOT_REQUIRED_FIELDS = (
    "snapshot_id",
    "snapshot_type",
    "snapshot_source",
    "snapshot_rank",
    "snapshot_date",
    "betting_day",
    "betting_day_start_local",
    "betting_day_end_local",
    "snapshot_created_at_utc",
    "results_status",
)


def _rows_missing_snapshot_metadata(rows: List[Dict[str, Any]]) -> bool:
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        for key in SNAPSHOT_REQUIRED_FIELDS:
            if row.get(key) in (None, ""):
                return True
    return False


def _write_snapshot_json(path: Path, rows: List[Dict[str, Any]], *, snapshot_type: str, context: Dict[str, str]) -> None:
    """Write immutable snapshot rows, repairing only missing metadata if needed.

    The pick list and market/model fields remain immutable. If an older dated
    snapshot exists without metadata, enrich existing rows in place so Results
    and Telegram can identify the morning snapshot safely.
    """
    if path.exists():
        try:
            existing_payload = json.loads(path.read_text(encoding="utf-8"))
            existing_rows = existing_payload if isinstance(existing_payload, list) else []
        except Exception:
            existing_rows = []
        if existing_rows and _rows_missing_snapshot_metadata(existing_rows):
            repaired_rows = _snapshot_rows(existing_rows, snapshot_type=snapshot_type, context=context)
            path.write_text(json.dumps(repaired_rows, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"Repaired missing snapshot metadata without changing picks: {path}")
        else:
            print(f"Immutable snapshot exists, preserving first file: {path}")
        return
    path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")


def _write_results_foundation_snapshots(
    all_rows: List[Dict[str, Any]],
    top7_rows: List[Dict[str, Any]],
    run_date: Optional[str],
    output_root: str,
) -> Dict[str, str]:
    """Store immutable morning snapshots for future Results evaluation."""
    context = _betting_day_context(run_date)
    day = context["betting_day"]
    year = day[:4]
    root = Path(output_root) / "snapshots" / year
    root.mkdir(parents=True, exist_ok=True)
    top7_path = root / f"{day}_corq_top7_snapshot.json"
    all_path = root / f"{day}_all_audit_snapshot.json"
    top7_snapshot_rows = _snapshot_rows(top7_rows, snapshot_type="CORQ_TOP7", context=context)
    all_snapshot_rows = _snapshot_rows(all_rows, snapshot_type="ALL_AUDIT", context=context)
    _write_snapshot_json(top7_path, top7_snapshot_rows, snapshot_type="CORQ_TOP7", context=context)
    _write_snapshot_json(all_path, all_snapshot_rows, snapshot_type="ALL_AUDIT", context=context)
    latest_root = Path(output_root) / "snapshots"
    latest_root.mkdir(parents=True, exist_ok=True)
    # latest_* points to the immutable dated snapshot for the current betting day.
    (latest_root / "latest_corq_top7_snapshot.json").write_text(top7_path.read_text(encoding="utf-8"), encoding="utf-8")
    (latest_root / "latest_all_audit_snapshot.json").write_text(all_path.read_text(encoding="utf-8"), encoding="utf-8")
    manifest_path = latest_root / "latest_corq_top7_snapshot_manifest.json"
    manifest_path.write_text(json.dumps({
        **context,
        "snapshot_source": "CORQ_DAILY",
        "snapshot_type": "CORQ_TOP7",
        "policy": "immutable_first_snapshot_wins_0600_betting_day",
        "dated_snapshot": str(top7_path),
        "latest_snapshot": str(latest_root / "latest_corq_top7_snapshot.json"),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    return {
        "corq_top7_snapshot": str(top7_path),
        "all_audit_snapshot": str(all_path),
        "latest_corq_top7_snapshot": str(latest_root / "latest_corq_top7_snapshot.json"),
        "latest_all_audit_snapshot": str(latest_root / "latest_all_audit_snapshot.json"),
        "latest_corq_top7_snapshot_manifest": str(manifest_path),
        "betting_day": day,
        "betting_day_start_local": context["betting_day_start_local"],
        "betting_day_end_local": context["betting_day_end_local"],
    }



# ---------------------------------------------------------------------------
# CloQ-priority CorQ finalizer
# ---------------------------------------------------------------------------
CORQ_CLOQ_PRIORITY_MODEL_VERSION = "CORQ_TOP7_CLOQ_PRIORITY_FILL_V1"


def _json_rows_local(obj: Any) -> List[Dict[str, Any]]:
    if isinstance(obj, list):
        return [x for x in obj if isinstance(x, dict)]
    if isinstance(obj, dict):
        for key in ("rows", "items", "top7", "all", "picks", "records", "data"):
            val = obj.get(key)
            if isinstance(val, list):
                return [x for x in val if isinstance(x, dict)]
    return []


def _read_json_local(path: Path, default: Any) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default
    return default


def _write_json_local(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def _priority_norm_text(value: Any) -> str:
    text = str(value or "").strip().lower()
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def _priority_event_id(row: Dict[str, Any]) -> str:
    raw = row.get("raw") if isinstance(row.get("raw"), dict) else {}
    for key in ("event_id", "match_id", "id", "fixture_id", "api_match_id", "custom_id", "customId"):
        value = row.get(key)
        if value not in (None, ""):
            return str(value).strip()
    for key in ("id", "customId", "custom_id"):
        value = raw.get(key)
        if value not in (None, ""):
            return str(value).strip()
    return ""


def _priority_pick_name(row: Dict[str, Any]) -> str:
    for key in ("pick", "top7_pick", "corq_pick", "cloq_pick", "selected_pick", "selected_player", "predicted_winner", "player", "player1", "home"):
        value = row.get(key)
        if value not in (None, "", "—", "-"):
            return str(value).strip()
    return ""


def _priority_opponent_name(row: Dict[str, Any]) -> str:
    for key in ("opponent", "opponent_name", "opp", "top7_opponent", "corq_opponent", "player2", "away"):
        value = row.get(key)
        if value not in (None, "", "—", "-"):
            return str(value).strip()
    return ""


def _priority_start_day(row: Dict[str, Any]) -> str:
    for key in ("betting_day", "snapshot_date", "snapshot_functional_day", "functional_day", "date", "match_date", "start_date"):
        value = row.get(key)
        if value:
            return str(value).strip()[:10]
    for key in ("start_time_utc", "match_time_utc", "start_time", "match_time", "scheduled_at"):
        value = row.get(key)
        if value:
            return str(value).strip()[:10]
    return ""


def _priority_match_key(row: Dict[str, Any]) -> str:
    eid = _priority_event_id(row)
    if eid:
        return "event:" + eid
    names = sorted([_priority_norm_text(_priority_pick_name(row)), _priority_norm_text(_priority_opponent_name(row))])
    names = [n for n in names if n]
    if len(names) >= 2:
        return "names:" + "|".join(names) + "|" + _priority_start_day(row)
    return ""


def _load_cloq_priority_keys(output_root: str = "outputs") -> set[str]:
    root = Path(output_root)
    paths = [
        root / "cloq" / "latest_cloq.json",
        root / "snapshots" / "latest_cloq_snapshot.json",
    ]
    keys: set[str] = set()
    for path in paths:
        rows = _json_rows_local(_read_json_local(path, []))
        for row in rows:
            key = _priority_match_key(row)
            if key:
                keys.add(key)
        if keys:
            break
    return keys


def _apply_cloq_priority_filter(ranked_rows: List[Dict[str, Any]], output_root: str = "outputs") -> tuple[List[Dict[str, Any]], List[Dict[str, Any]], set[str]]:
    cloq_keys = _load_cloq_priority_keys(output_root)
    if not cloq_keys:
        return ranked_rows, [], set()
    kept: List[Dict[str, Any]] = []
    skipped: List[Dict[str, Any]] = []
    for row in ranked_rows or []:
        key = _priority_match_key(row)
        if key and key in cloq_keys:
            item = dict(row)
            item["corq_skipped_by_cloq_priority"] = True
            item["corq_cloq_priority_match_key"] = key
            item["corq_cloq_priority_reason"] = "CORQ_SKIPPED_CLOQ_PRIORITY_OVERLAP"
            skipped.append(item)
            continue
        kept.append(row)
    return kept, skipped, cloq_keys


def finalize_top7_from_latest_all(output_root: str = "outputs", run_date: Optional[str] = None, top_n: int = 7) -> Dict[str, Any]:
    """Finalize CorQ TOP7 after CloQ has been generated.

    This avoids duplicate public matches by giving CloQ priority. CorQ is not
    shrunk after TOP7 selection; instead, the entire ranked CorQ candidate pool
    is filtered against CloQ and then filled back to top_n from remaining rows.
    """
    root = Path(output_root)
    latest_all = root / "latest_all.json"
    all_rows = _json_rows_local(_read_json_local(latest_all, []))
    if not all_rows:
        raise SystemExit(f"Cannot finalize CorQ TOP7: no rows in {latest_all}")

    ranking = rank_corq(all_rows)
    filtered_ranking, skipped_rows, cloq_keys = _apply_cloq_priority_filter(ranking, output_root=output_root)
    top7 = top7_from_ranking(filtered_ranking, top_n=top_n)

    for idx, row in enumerate(top7, start=1):
        row["top7_rank"] = idx
        row["snapshot_rank"] = idx
        row["corq_cloq_priority_model_version"] = CORQ_CLOQ_PRIORITY_MODEL_VERSION
        row["corq_cloq_priority_enabled"] = True
        row["corq_cloq_priority_cloq_key_count"] = len(cloq_keys)
        row["corq_cloq_priority_skipped_count"] = len(skipped_rows)

    top7_paths = save_top7(top7, run_date=run_date, output_root=output_root)
    snapshot_paths = _write_results_foundation_snapshots(all_rows, top7, run_date=run_date, output_root=output_root)
    skipped_path = root / "snapshots" / "latest_corq_cloq_priority_skipped.json"
    _write_json_local(skipped_path, skipped_rows)

    manifest = {
        "runtime": "corq_top7_cloq_priority_finalizer",
        "model_version": CORQ_CLOQ_PRIORITY_MODEL_VERSION,
        "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "run_date": run_date or snapshot_paths.get("betting_day"),
        "betting_day": snapshot_paths.get("betting_day"),
        "betting_day_start_local": snapshot_paths.get("betting_day_start_local"),
        "betting_day_end_local": snapshot_paths.get("betting_day_end_local"),
        "input": str(latest_all),
        "all_count": len(all_rows),
        "ranked_count": len(ranking),
        "cloq_priority_key_count": len(cloq_keys),
        "corq_candidates_after_cloq_filter": len(filtered_ranking),
        "corq_skipped_by_cloq_priority_count": len(skipped_rows),
        "top7_count": len(top7),
        "top7_target": top_n,
        "outputs": {"top7": top7_paths, "snapshots": snapshot_paths, "skipped": str(skipped_path)},
    }
    manifest_paths = save_run_manifest(manifest, run_date=run_date, output_root=output_root)
    manifest["outputs"]["manifest"] = manifest_paths
    return manifest

def run_daily(input_path: Optional[str] = None, output_root: str = "outputs", run_date: Optional[str] = None) -> Dict[str, Any]:
    started_at = datetime.now(timezone.utc).isoformat()
    raw_candidates = load_candidates(input_path)
    candidates = [repair_candidate_side(candidate) for candidate in raw_candidates]
    thinq_service = _load_thinq_service()
    tennisapi_rankings = _load_tennisapi_rankings_info(output_root)
    try:
        from corq.rapidapi_client import RapidApiClient  # type: ignore
        api_h2h_client = RapidApiClient()
    except Exception as exc:
        api_h2h_client = None
        print(f"TENNISAPI H2H STATS CLIENT UNAVAILABLE: {exc}")
    api_h2h_request_state = {"count": 0}

    scored: List[Dict[str, Any]] = []
    for candidate in candidates:
        enriched = _enrich_with_thinq(candidate, thinq_service)
        enriched = _enrich_with_api_h2h_stats(enriched, api_h2h_client, api_h2h_request_state)
        prediction = build_corq_prediction(enriched)
        prediction = _enrich_with_tennisapi_ranking_info(prediction, tennisapi_rankings)
        prediction = _enrich_with_ta_profile_context(prediction)
        prediction = _enrich_with_sets_games(prediction)
        prediction = _enrich_with_marq(prediction)
        prediction = apply_corq_market_calibration(prediction)
        prediction = _enrich_with_price_value(prediction)
        scored.append(prediction)

    all_view = make_all_match_view(scored)
    ranking = rank_corq(scored)
    top7 = top7_from_ranking(ranking, top_n=7)

    all_paths = save_all(all_view, run_date=run_date, output_root=output_root)
    top7_paths = save_top7(top7, run_date=run_date, output_root=output_root)
    snapshot_paths = _write_results_foundation_snapshots(all_view, top7, run_date=run_date, output_root=output_root)
    manifest = {
        "runtime": "corq_daily_side_safe",
        "started_at_utc": started_at,
        "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "run_date": run_date or _betting_day_context().get("betting_day") or date.today().isoformat(),
        "betting_day": snapshot_paths.get("betting_day"),
        "betting_day_start_local": snapshot_paths.get("betting_day_start_local"),
        "betting_day_end_local": snapshot_paths.get("betting_day_end_local"),
        "input_path": input_path,
        "candidate_count": len(candidates),
        "scored_count": len(scored),
        "all_count": len(all_view),
        "ranked_count": len(ranking),
        "top7_count": len(top7),
        "thinq_service_available": thinq_service is not None and not isinstance(thinq_service, _UnavailableThinqService),
        "thinq_service_module": getattr(thinq_service, "_corq_import_module", None),
        "thinq_service_file": getattr(thinq_service, "_corq_import_file", None),
        "thinq_service_import_diagnostics": getattr(thinq_service, "_corq_import_diagnostics", THINQ_SERVICE_LOAD_DIAGNOSTICS),
        "side_safety": {
            "player1_definition": "HOME_API_FIRST_SIDE",
            "player2_definition": "AWAY_API_SECOND_SIDE",
            "pick_definition": "DERIVED_FROM_PICK_SIDE",
        },
        "outputs": {"all": all_paths, "top7": top7_paths, "snapshots": snapshot_paths},
    }
    manifest_paths = save_run_manifest(manifest, run_date=run_date, output_root=output_root)
    manifest["outputs"]["manifest"] = manifest_paths
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Run CORQ daily runtime")
    parser.add_argument("--input", dest="input_path", default=None, help="Optional path to candidates/matches JSON")
    parser.add_argument("--output-root", default="outputs", help="Output root directory")
    parser.add_argument("--date", dest="run_date", default=None, help="Run date YYYY-MM-DD")
    parser.add_argument("--finalize-top7-from-latest-all", action="store_true", help="Finalize TOP7 from outputs/latest_all.json after CloQ has priority")
    args = parser.parse_args()

    if args.finalize_top7_from_latest_all:
        manifest = finalize_top7_from_latest_all(output_root=args.output_root, run_date=args.run_date, top_n=7)
        print("CORQ CloQ-priority TOP7 finalizer finished")
        print(f"ALL: {manifest['all_count']}")
        print(f"Skipped by CloQ priority: {manifest['corq_skipped_by_cloq_priority_count']}")
        print(f"TOP7: {manifest['top7_count']}")
        return

    manifest = run_daily(input_path=args.input_path, output_root=args.output_root, run_date=args.run_date)
    print("CORQ runtime finished")
    print(f"Candidates: {manifest['candidate_count']}")
    print(f"ALL: {manifest['all_count']}")
    print(f"TOP7: {manifest['top7_count']}")


if __name__ == "__main__":
    main()
