from __future__ import annotations

import csv
import json
import os
import re
import unicodedata
from dataclasses import dataclass, asdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

# ThinQ History loader v2
# ----------------------
# Goal:
# - Use only intentional historical data sources.
# - Never use runtime outputs/snapshots as historical training data by default.
# - Parse Sackmann/Tennis-Major-style CSVs and generic JSON/JSONL safely.
# - Provide robust player-name aliases, including First Last and Last First variants.

DEFAULT_HISTORY_SEARCH_DIRS: Tuple[Path, ...] = (
    Path("data/history/sackmann_archive/tml"),
    Path("data/history"),
    Path("thinq/data/history"),
    Path("data/sackmann"),
    Path("thinq/data/sackmann"),
)

# These are intentionally excluded from the default source list. Runtime outputs
# are generated by today's model and can contaminate Recent Form with current or
# future candidates. Enable manually only for forensic checks via env.
RUNTIME_HISTORY_DIRS: Tuple[Path, ...] = (
    Path("outputs/results"),
    Path("outputs/results/all"),
    Path("outputs/results/corq"),
    Path("outputs/snapshots"),
    Path("outputs/snapshots/all"),
)

HISTORY_FILE_PATTERNS = ("*.csv", "*.json", "*.jsonl")

_SURFACE_MAP = {
    "hard": "Hard",
    "hardcourt": "Hard",
    "hardcourt outdoor": "Hard",
    "outdoor hard": "Hard",
    "indoor hard": "Hard",
    "clay": "Clay",
    "red clay": "Clay",
    "green clay": "Clay",
    "grass": "Grass",
    "carpet": "Carpet",
    "carpet indoor": "Carpet",
}

_TRANSLATE = str.maketrans({
    "ł": "l", "Ł": "L",
    "đ": "d", "Đ": "D",
    "ð": "d", "Ð": "D",
    "þ": "th", "Þ": "Th",
    "ß": "ss",
    "ø": "o", "Ø": "O",
    "æ": "ae", "Æ": "Ae",
    "œ": "oe", "Œ": "Oe",
    "š": "s", "Š": "S",
    "č": "c", "Č": "C",
    "ž": "z", "Ž": "Z",
    "ć": "c", "Ć": "C",
    "ń": "n", "Ń": "N",
})


def _name_from_obj(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, dict):
        for key in (
            "name", "fullName", "full_name", "displayName", "display_name",
            "shortName", "short_name", "player", "player_name", "slug",
        ):
            if value.get(key):
                return str(value.get(key))
        return ""
    return str(value)


def normalize_name(value: Any) -> str:
    text = _name_from_obj(value).strip().lower().translate(_TRANSLATE)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace(".", " ").replace("-", " ").replace("_", " ").replace(",", " ").replace("'", " ")
    text = re.sub(r"[^a-z0-9 ]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def compact_name(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", normalize_name(value))


def name_aliases(value: Any) -> List[str]:
    """Return normalized aliases for player name matching.

    Handles common source differences:
    - "Ann Li" vs "Li Ann"
    - "Li, Ann" vs "Ann Li"
    - compact spelling fallback
    """
    raw = _name_from_obj(value).strip()
    norm = normalize_name(raw)
    aliases: List[str] = []
    if norm:
        aliases.append(norm)
        parts = norm.split()
        if len(parts) == 2:
            aliases.append(f"{parts[1]} {parts[0]}")
        elif len(parts) > 2:
            aliases.append(" ".join(parts[1:] + parts[:1]))
            aliases.append(" ".join(parts[-1:] + parts[:-1]))
    if "," in raw:
        left, right = raw.split(",", 1)
        flipped = normalize_name(f"{right} {left}")
        if flipped:
            aliases.append(flipped)
    # Preserve order, remove duplicates and empties.
    out: List[str] = []
    for alias in aliases:
        alias = normalize_name(alias)
        if alias and alias not in out:
            out.append(alias)
    return out


def normalize_surface(value: Any) -> str:
    raw = str(value or "").strip()
    key = raw.lower()
    if key in _SURFACE_MAP:
        return _SURFACE_MAP[key]
    for marker, normalized in _SURFACE_MAP.items():
        if marker in key:
            return normalized
    return raw.title() if raw else "Unknown"


def _clean_key(k: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(k or "").lower())


def _norm_row(row: Dict[str, Any]) -> Dict[str, Any]:
    out = dict(row)
    for k, v in row.items():
        out[_clean_key(k)] = v
    return out


def _first(row: Dict[str, Any], names: Sequence[str]) -> Any:
    for name in names:
        if name in row and row.get(name) not in (None, ""):
            return row.get(name)
        ck = _clean_key(name)
        if ck in row and row.get(ck) not in (None, ""):
            return row.get(ck)
    return None


def _to_int(value: Any) -> Optional[int]:
    try:
        if value in (None, "", "nan", "NaN"):
            return None
        return int(float(value))
    except Exception:
        return None


def _parse_date(value: Any) -> str:
    if value in (None, ""):
        return ""
    text = str(value).strip()
    if re.fullmatch(r"\d{8}", text):
        return f"{text[:4]}-{text[4:6]}-{text[6:8]}"
    if re.fullmatch(r"\d{10}", text):
        try:
            from datetime import datetime, timezone
            return datetime.fromtimestamp(int(text), tz=timezone.utc).date().isoformat()
        except Exception:
            pass
    if len(text) >= 10 and text[4:5] == "-":
        return text[:10]
    return text


@dataclass(frozen=True)
class HistoryMatch:
    date: str
    winner: str
    loser: str
    surface: str = "Unknown"
    level: str = ""
    tournament: str = ""
    winner_rank: Optional[int] = None
    loser_rank: Optional[int] = None
    source_file: str = ""

    @property
    def winner_key(self) -> str:
        return normalize_name(self.winner)

    @property
    def loser_key(self) -> str:
        return normalize_name(self.loser)

    @property
    def winner_aliases(self) -> List[str]:
        return name_aliases(self.winner)

    @property
    def loser_aliases(self) -> List[str]:
        return name_aliases(self.loser)

    def involves(self, player_key: str) -> bool:
        return player_key in set(self.winner_aliases + self.loser_aliases)

    def player_won(self, player_key: str) -> Optional[bool]:
        if player_key in set(self.winner_aliases):
            return True
        if player_key in set(self.loser_aliases):
            return False
        return None

    def opponent_rank_for(self, player_key: str) -> Optional[int]:
        if player_key in set(self.winner_aliases):
            return self.loser_rank
        if player_key in set(self.loser_aliases):
            return self.winner_rank
        return None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def _env_dirs(name: str) -> List[Path]:
    raw = os.getenv(name, "")
    out: List[Path] = []
    for part in raw.split(os.pathsep):
        part = part.strip()
        if part:
            out.append(Path(part))
    return out


def search_dirs() -> List[Path]:
    dirs: List[Path] = []
    dirs.extend(_env_dirs("THINQ_HISTORY_DIRS"))
    if not dirs:
        dirs.extend(DEFAULT_HISTORY_SEARCH_DIRS)
    dirs.extend(_env_dirs("THINQ_HISTORY_EXTRA_DIRS"))
    if os.getenv("THINQ_HISTORY_INCLUDE_RUNTIME_OUTPUTS", "0").strip().lower() in {"1", "true", "yes", "y"}:
        dirs.extend(RUNTIME_HISTORY_DIRS)
    # Preserve order, remove duplicates.
    out: List[Path] = []
    for d in dirs:
        if d not in out:
            out.append(d)
    return out


def _candidate_files() -> List[Path]:
    files: List[Path] = []
    for root in search_dirs():
        if root.exists():
            for pattern in HISTORY_FILE_PATTERNS:
                files.extend(root.rglob(pattern))
    ignored = {"bootstrap_manifest.json", "latest_all.json", "latest_top7.json", "latest_manifest.json"}
    return sorted({p for p in files if p.name not in ignored})


def _score_current(value: Any) -> Optional[int]:
    if isinstance(value, dict):
        return _to_int(value.get("current") or value.get("score") or value.get("sets") or value.get("display"))
    return _to_int(value)


def _match_from_row(raw_row: Dict[str, Any], source: Path) -> Optional[HistoryMatch]:
    row = _norm_row(raw_row)

    winner = _first(row, [
        "winner_name", "winner", "winnerName", "match_winner", "matchWinner",
        "player_won", "winner_player", "winnerplayer", "winnerTeam", "winner_team",
    ])
    loser = _first(row, [
        "loser_name", "loser", "loserName", "match_loser", "matchLoser",
        "loser_player", "loserplayer", "loserTeam", "loser_team",
    ])

    p1 = _first(row, ["player1", "player_1", "home", "home_player", "homeTeam", "home_name", "home_name_full", "p1", "Player 1"])
    p2 = _first(row, ["player2", "player_2", "away", "away_player", "awayTeam", "away_name", "away_name_full", "p2", "Player 2"])
    p1_name = _name_from_obj(p1)
    p2_name = _name_from_obj(p2)

    winner_code = _to_int(_first(row, ["winnerCode", "winner_code", "winnercode"]))
    if (not winner or not loser) and p1_name and p2_name and winner_code in {1, 2}:
        winner, loser = (p1_name, p2_name) if winner_code == 1 else (p2_name, p1_name)

    if (not loser) and p1_name and p2_name and winner:
        w_aliases = set(name_aliases(winner))
        if set(name_aliases(p1_name)).intersection(w_aliases):
            loser = p2_name
        elif set(name_aliases(p2_name)).intersection(w_aliases):
            loser = p1_name

    if (not winner or not loser) and p1_name and p2_name:
        home_score = _score_current(_first(row, ["homeScore", "home_score", "p1_score", "homeCurrent", "homescorecurrent"] ))
        away_score = _score_current(_first(row, ["awayScore", "away_score", "p2_score", "awayCurrent", "awayscorecurrent"] ))
        if home_score is not None and away_score is not None and home_score != away_score:
            winner, loser = (p1_name, p2_name) if home_score > away_score else (p2_name, p1_name)

    if not winner or not loser:
        return None

    date_value = _first(row, [
        "tourney_date", "date", "match_date", "startDate", "start_date", "start_time",
        "startTimestamp", "start_timestamp", "time", "Date",
    ])
    match_date = _parse_date(date_value)
    if not match_date:
        return None

    return HistoryMatch(
        date=match_date,
        winner=_name_from_obj(winner),
        loser=_name_from_obj(loser),
        surface=normalize_surface(_first(row, ["surface", "surfaceType", "court", "court_surface", "Surface"])),
        level=str(_first(row, ["tourney_level", "level", "category", "tour", "competition", "Level"] ) or ""),
        tournament=str(_first(row, ["tourney_name", "tournament", "event", "competition_name", "Tournament"] ) or ""),
        winner_rank=_to_int(_first(row, ["winner_rank", "winnerRank", "winner_ranking", "wrank"])),
        loser_rank=_to_int(_first(row, ["loser_rank", "loserRank", "loser_ranking", "lrank"])),
        source_file=str(source),
    )


def _records_from_json_payload(payload: Any) -> List[Dict[str, Any]]:
    if isinstance(payload, list):
        return [x for x in payload if isinstance(x, dict)]
    if isinstance(payload, dict):
        for key in ("matches", "results", "items", "data", "events", "rows"):
            value = payload.get(key)
            if isinstance(value, list):
                return [x for x in value if isinstance(x, dict)]
        return [payload]
    return []


def _matches_from_json_payload(payload: Any, source: Path) -> List[HistoryMatch]:
    out: List[HistoryMatch] = []
    for record in _records_from_json_payload(payload):
        match = _match_from_row(record, source)
        if match:
            out.append(match)
    return out


@lru_cache(maxsize=1)
def load_history_matches() -> Tuple[HistoryMatch, ...]:
    out: List[HistoryMatch] = []
    for path in _candidate_files():
        try:
            if path.suffix.lower() == ".csv":
                with path.open("r", encoding="utf-8-sig", newline="") as handle:
                    for row in csv.DictReader(handle):
                        match = _match_from_row(row, path)
                        if match:
                            out.append(match)
            elif path.suffix.lower() == ".jsonl":
                with path.open("r", encoding="utf-8") as handle:
                    for line in handle:
                        line = line.strip()
                        if not line:
                            continue
                        match = _match_from_row(json.loads(line), path)
                        if match:
                            out.append(match)
            elif path.suffix.lower() == ".json":
                out.extend(_matches_from_json_payload(json.loads(path.read_text(encoding="utf-8")), path))
        except Exception:
            # A bad history file must not break the daily runtime.
            continue
    # Deduplicate because archive folders can overlap with root data/history.
    dedup: Dict[Tuple[str, str, str, str, str], HistoryMatch] = {}
    for m in out:
        key = (m.date, normalize_name(m.winner), normalize_name(m.loser), m.tournament, m.surface)
        dedup.setdefault(key, m)
    data = list(dedup.values())
    data.sort(key=lambda m: m.date or "", reverse=True)
    return tuple(data)


@lru_cache(maxsize=1)
def _player_index() -> Dict[str, Tuple[HistoryMatch, ...]]:
    index: Dict[str, List[HistoryMatch]] = {}
    for match in load_history_matches():
        for alias in match.winner_aliases:
            index.setdefault(alias, []).append(match)
        for alias in match.loser_aliases:
            index.setdefault(alias, []).append(match)
    return {key: tuple(value) for key, value in index.items()}


def get_player_matches(player: str, limit: Optional[int] = None) -> List[HistoryMatch]:
    aliases = name_aliases(player)
    seen = set()
    matches: List[HistoryMatch] = []
    index = _player_index()
    for alias in aliases:
        for m in index.get(alias, ()):
            key = (m.date, m.winner, m.loser, m.tournament, m.surface, m.source_file)
            if key not in seen:
                seen.add(key)
                matches.append(m)
    matches.sort(key=lambda m: m.date or "", reverse=True)
    return matches[:limit] if limit else matches


def history_data_status() -> Dict[str, Any]:
    files = _candidate_files()
    matches = load_history_matches()
    return {
        "status": "OK" if matches else "NO_DATA",
        "match_count": len(matches),
        "file_count": len(files),
        "search_dirs": [str(p) for p in search_dirs()],
        "sample_files": [str(p) for p in files[:12]],
        "runtime_outputs_included": os.getenv("THINQ_HISTORY_INCLUDE_RUNTIME_OUTPUTS", "0").strip().lower() in {"1", "true", "yes", "y"},
    }


def clear_history_cache() -> None:
    load_history_matches.cache_clear()
    _player_index.cache_clear()
